/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0x51, 0x73, 0x85, 0x91, 0x1B, 0xC7, 0x66, 0x7B}
#define VIAL_UNLOCK_COMBO_ROWS { 2, 2 }
#define VIAL_UNLOCK_COMBO_COLS { 9, 8 }
#define DYNAMIC_KEYMAP_LAYER_COUNT 8

#define EXTERNAL_EEPROM_BYTE_COUNT 32768
#define EEPROM_SIZE 32768
#define EXTERNAL_EEPROM_PAGE_SIZE 64

#define PERMISSIVE_HOLD
#undef TAPPING_TERM
#define TAPPING_TERM 175
#define IGNORE_MOD_TAP_INTERRUPT

//#define NO_ACTION_ONESHOT
