// Copyright 2022 Stefan Kerkmann
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

//#define QMK_WAITING_TEST_BUSY_PIN GP8
//#define QMK_WAITING_TEST_YIELD_PIN GP9

//#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
//#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED GP25
//#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U

//#define ADC_PIN GP26
#define PS2M_ENABLE
#define PS2M_MOUSE_ENABLE
#define PS2M_PIO_USE_PIO1
#define PS2M_DATA_PIN GP18
#define PS2M_CLOCK_PIN GP19
